# Generated by Django 5.0.6 on 2024-07-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_remove_banktransactionmodel_current_amount_and_more'),
        ('vyaparapp', '0039_auto_20240517_0852'),
    ]

    operations = [
    ]
